version: '3.1'

services: 
  crucible:
    build: 
      context: .
      dockerfile: Dockerfile-crucible
    ports: 
      - 8060:8060
  
  bamboo:
    build: 
      context: .
      dockerfile: Dockerfile-bamboo
    ports: 
      - 8085:8085
    